Python/Django/labhost/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', views.user_home, name='home'),
    path('login/', views.login_page, name='login'),
    path('login_user/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('save_user/', views.save_user, name='save_user'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

Python/Django/labhost/labhost/urls.py
from django.contrib import admin
from django.urls import path, include
from . import mainsite

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/notrap/', admin.site.urls),
    path('', mainsite.index),
    path('contacts/', include('contacts.urls')),
    path('redir/', include('urlshortener.urls')),
    path('accounts/', include('accounts.urls')),
    path('library/', include('library.urls')),
    path('todos/', include('todos.urls')),
]

Python/Django/labhost/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Python/Django/labhost/todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('complete/', views.complete, name='complete'),
    path('delete/', views.delete, name='delete'),
    path('save/', views.save, name='save'),
]

Python/Django/labhost/todos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='todos')
    todo = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username + "-" + self.todo

Python/Django/labhost/todos/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Todo
import json

@login_required
def index(request):
    user = request.user
    initialTodos = Todo.objects.filter(user=user, completed=False)
    initialCompleted = Todo.objects.filter(user=user, completed=True)
    initialTodosJS = "["
    for todo_item in initialTodos:
        initialTodosJS += '{"todo": "' + todo_item.todo + '", "id": ' + str(todo_item.id) + "},"
    initialTodosJS += "]"
    initialCompletedJS = "["
    for todo_item in initialCompleted:
        initialCompletedJS += '{"todo": "' + todo_item.todo + '", "id": ' + str(todo_item.id) + "},"
    initialCompletedJS += "]"
    context = {
        'initialTodos': initialTodosJS,
        'initialCompleted': initialCompletedJS,
    }
    return render(request, 'todos/index.html', context)

@login_required
def save(request):
    parsed = json.loads(request.body)
    if parsed['todo']:
        user = request.user
        new = Todo(todo=parsed['todo'], user=user)
        new.save()
        return HttpResponse(new.id)

@login_required
def complete(request):
    parsed = json.loads(request.body)
    user = request.user
    todo = Todo.objects.filter(id=parsed['id']).first()
    print(todo)
    if todo:
        if todo.user == user:
            if parsed['completed'] == 'true':
                todo.completed = True
                todo.save()
                return HttpResponse('')
            if parsed['completed'] == 'false':
                todo.completed = False
                todo.save()
                return HttpResponse('')
            return HttpResponse('Error: no operation specified')
    return HttpResponse('Error: specified todo does not exist')

@login_required
def delete(request):
    parsed = json.loads(request.body)
    user = request.user
    todo = Todo.objects.filter(id=parsed['id']).first()
    if todo:
        if todo.user == user:
            todo.delete()
            return HttpResponse('')
    return HttpResponse('Error: specified todo does not exist')

Python/Django/labhost/todos/templates/todos/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <title>todos</title>
    <style type="text/css">
      .cardHolder{
        display: flex;
        flex-direction: column;
      }
      li button{
        margin-left: 8px;
      }
      nav{
        display: flex;
        justify-content: flex-end;
        flex-direction: row;
        width: 100%;
      }
      nav>*{
        margin: 3px 8px;
        color: black;
      }
    </style>
  </head>
  <body>
    <nav>
      <span>{{user.username}}</span>
      <a href="{% url 'accounts:logout' %}">logout</a>
    </nav>
    <div id="app">
      <div v-if="errorMessage">[[errorMessage]]</div>
      <input type="text" v-model="newTodo" placeholder="new todo"><button @click='saveTodo'>save</button>
      <h3>todo</h3>
      <ul>
        <li v-for="todo in todoList">[[todo.todo]]<button v-on:click="completeTodo(todo)">completed</button></li>
      </ul>
      <h3>completed</h3>
      <ul>
        <li v-for="todo in completedList">[[todo.todo]]<button v-on:click="uncompleteTodo(todo)">completed</button><button v-on:click="deleteTodo(todo)">delete</button></li>
      </ul>
    </div>
    <script type="text/javascript">
      let app = new Vue({
        el: '#app',
        delimiters: ['[[',']]'],
        data: {
          todoList: {{initialTodos|safe}},
          completedList: {{initialCompleted|safe}},
          newTodo: '',
          errorMessage: '',
        },
        methods: {
          saveTodo: function() {
            axios({
              method: 'post',
              url: '{% url 'todos:save' %}',
              headers: {
                'X-CSRFToken': '{{csrf_token}}'
              },
              data: {
                'todo': this.newTodo
              }
            }).then(response => {
              if (response.data){
                this.todoList.push({'todo': this.newTodo, 'id': response.data})
              }
            })
          },
          completeTodo: function(todo) {
            let todoIndex = this.todoList.indexOf(todo)
            this.todoList.splice(todoIndex,1)
            this.completedList.unshift(todo)
            axios({
              method: 'post',
              url: '{% url 'todos:complete' %}',
              headers: {
                'X-CSRFToken': '{{csrf_token}}'
              },
              data: {
                'id': todo.id,
                'completed': 'true'
              }
            }).then(response => {
              if (response.data){
                this.errorMessage = response.data
              }
            })
          },
          uncompleteTodo: function(todo) {
            let todoIndex = this.completedList.indexOf(todo)
            this.completedList.splice(todoIndex,1)
            this.todoList.unshift(todo)
            axios({
              method: 'post',
              url: '{% url 'todos:complete' %}',
              headers: {
                'X-CSRFToken': '{{csrf_token}}'
              },
              data: {
                'id': todo.id,
                'completed': 'false'
              }
            }).then(response => {
              if (response.data){
                this.errorMessage = response.data
              }
            })
          },
          deleteTodo: function(todo) {
            let todoIndex = this.completedList.indexOf(todo)
            this.completedList.splice(todoIndex,1)
            axios({
              method: 'post',
              url: '{% url 'todos:delete' %}',
              headers: {
                'X-CSRFToken': '{{csrf_token}}'
              },
              data: {
                'id': todo.id,
              }
            }).then(response => {
              if (response.data){
                this.errorMessage = response.data
              }
            })
          },
        }
      })
    </script>
  </body>
</html>