Python/Django/labhost/contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:contact_id>/', views.contact_detail, name='contact_detail'),
    path('new/', views.new_contact, name='new_contact'),
    path('<int:contact_id>/edit/', views.edit_contact, name='edit_contact'),
    path('new/submit/', views.write_new_contact, name='write_new_contact'),
    path('<int:contact_id>/edit/submit/', views.write_edit_contact, name='write_edit_contact'),
    path('<int:contact_id>/delete/', views.delete_contact, name='delete_contact'),
]

Python/Django/labhost/labhost/urls.py
from django.contrib import admin
from django.urls import path, include
from . import mainsite

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/notrap/', admin.site.urls),
    path('', mainsite.index),
    path('contacts/', include('contacts.urls')),
    path('redir/', include('urlshortener.urls')),
    path('accounts/', include('accounts.urls')),
    path('library/', include('library.urls')),
    path('todos/', include('todos.urls')),
]

Python/Django/labhost/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Python/Django/labhost/contacts/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    first_name = models.CharField(max_length=40, blank=True)
    last_name = models.CharField(max_length=40)
    birthday = models.DateField('birthday', blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True)
    is_cell = models.BooleanField(blank=True)
    def __str__(self):
        output = ""
        if self.first_name:
            output += self.first_name + ' '
        output += self.last_name
        return output

Python/Django/labhost/contacts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
import datetime

from .models import Contact

# Create your views here.
def index(request):
    contacts = Contact.objects.order_by('last_name')
    context = {'contacts': contacts}
    return render(request, 'contacts/index.html', context)

def contact_detail(request, contact_id):
    contact_data = Contact.objects.get(id=contact_id)
    birthday = contact_data.birthday
    context = {'contact': contact_data, 'birthday': birthday}
    return render(request, 'contacts/detail.html', context)

def new_contact(request):
    return render(request, 'contacts/new.html')

def edit_contact(request, contact_id):
    contact_data = Contact.objects.get(id=contact_id)
    birthday = datetime.datetime.strftime(contact_data.birthday, '%Y-%m-%d')
    context = {'contact': contact_data, 'birthday': birthday}
    return render(request, 'contacts/edit.html', context)

def write_new_contact(request):
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    if last_name == '':
        return HttpResponseRedirect(reverse('contacts:index'))
    birthday = request.POST['birthday']
    phone_number = request.POST['phone_number']
    if 'is_cell' in request.POST:
        is_cell = True
    else:
        is_cell = False
    new = Contact(first_name=first_name, last_name=last_name, birthday=birthday, phone_number=phone_number, is_cell=is_cell)
    new.save()
    return HttpResponseRedirect(reverse('contacts:index'))

def write_edit_contact(request, contact_id):
    contact_data = Contact.objects.get(id=contact_id)
    last_name = request.POST['last_name']
    if last_name:
        contact_data.last_name = last_name
    else:
        return HttpResponseRedirect(reverse('contacts:index'))
    contact_data.first_name = request.POST['first_name']
    contact_data.birthday = request.POST['birthday']
    contact_data.phone_number = request.POST['phone_number']
    if 'is_cell' in request.POST:
        contact_data.is_cell = True
    else:
        contact_data.is_cell = False
    contact_data.save()
    return HttpResponseRedirect(reverse('contacts:contact_detail', args=(contact_id,)))

def delete_contact(request, contact_id):
    contact = Contact.objects.get(id=contact_id)
    contact.delete()
    return HttpResponseRedirect(reverse('contacts:index'))

Python/Django/labhost/contacts/templates/contacts/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>{{ contact.first_name }} {{ contact.last_name }}</p>
    <p>{{ birthday }}</p>
    <p>{{ contact.phone_number }} {% if contact.is_cell %}(cell){% endif %}</p>
    <form class="" action="{% url 'contacts:edit_contact' contact.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="contact" value="{{contact.id}}">
      <input type="submit" value="Edit">
    </form>
    <form class="" action="{% url 'contacts:delete_contact' contact.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="contact" value="{{contact.id}}">
      <input type="submit" value="Delete">
    </form>
    <a href="/contacts/">back to contacts list</a>
  </body>
</html>

Python/Django/labhost/contacts/templates/contacts/edit.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style type="text/css">
      #cell_check + label{
        text-decoration: line-through;

      }
      #cell_check:checked + label{
        text-decoration: none;
      }
      form{
        display: flex;
        flex-direction: column;
        width: 60%;
        margin: auto;
        background-color: grey;
        padding: 4px;
        min-height: 100vh;
        box-sizing: border-box;
      }
      body{
        margin: 0;
      }
      .smol{
        width: 300px;
        margin-bottom: 3px;
      }
      .sub_btn{
        align-self: center;
      }
      .cellphone{
        display: flex;
        align-items: center;
      }
    </style>
  </head>
  <body>
    <form class="" action="{% url 'contacts:write_edit_contact' contact.id %}" method="post">
      {% csrf_token %}
      <input class='smol' type="text" name="first_name" placeholder="first name" value="{{ contact.first_name }}">
      <input class='smol' type="text" name="last_name" placeholder="last name" value="{{ contact.last_name }}" required>
      <div class="smol">birthday: <input type="date" name="birthday" value="{{ birthday }}"></div>
      <input class='smol' type="text" name="phone_number" placeholder="phone number" value="{{ contact.phone_number }}">
      <div class="cellphone"><input id='cell_check' type="checkbox" name="is_cell" {% if contact.is_cell %}checked{% endif %}><label for="cell_check">cellphone</label></div>
      <input class="sub_btn" type="submit">
      <a href="/contacts/">back to contacts list</a>
    </form>
  </body>
</html>

Python/Django/labhost/contacts/templates/contacts/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style type="text/css">
      .button_link{
        border-radius: 2px;
        border: 1px solid grey;
        padding: 2px;
        background-color: whitesmoke;
        text-decoration: none;
        color: black;
      }
      .names{
        color: black;
      }

    </style>
  </head>
  <body>
    <h3>Contacts</h3>
    {% if not contacts %}
    <p>The contacts list is empty.</p>
    {% endif %}
    <ul>
      {% for contact in contacts %}
      <li><a class='names' href="/contacts/{{ contact.id }}">{{ contact.first_name }} {{ contact.last_name }}</a><form class="" action="{% url 'contacts:edit_contact' contact.id %}" method="post">{% csrf_token %}<input type="hidden" name="contact" value="{{ contact.id }}"><input type="submit" value="Edit"></form></li>
      {% endfor %}
    </ul>
    <a class="button_link" href="{% url 'contacts:new_contact' %}">Create new contact</a>
  </body>
</html>

Python/Django/labhost/contacts/templates/contacts/new.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style type="text/css">
      #cell_check + label{
        text-decoration: line-through;

      }
      #cell_check:checked + label{
        text-decoration: none;
      }
      form{
        display: flex;
        flex-direction: column;
        width: 60%;
        margin: auto;
        background-color: grey;
        padding: 4px;
        min-height: 100vh;
        box-sizing: border-box;
      }
      body{
        margin: 0;
      }
      .smol{
        width: 300px;
        margin-bottom: 3px;
      }
      .sub_btn{
        align-self: center;
      }
      .cellphone{
        display: flex;
        align-items: center;
      }
    </style>
  </head>
  <body>
    <form class="" action="{% url 'contacts:write_new_contact' %}" method="post">
      {% csrf_token %}
      <input class='smol' type="text" name="first_name" placeholder="first name">
      <input class='smol' type="text" name="last_name" placeholder="last name" required>
      <div class="smol">birthday: <input type="date" name="birthday"></div>
      <input class='smol' type="text" name="phone_number" placeholder="phone number">
      <div class="cellphone"><input id='cell_check' type="checkbox" name="is_cell"><label for="cell_check">cellphone</label></div>
      <input class="sub_btn" type="submit">
    </form>
    <a href="/contacts/">back to contacts list</a>
  </body>
</html>